# Generated by Django 5.0 on 2024-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_author_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isbn',
            field=models.CharField(default='None', max_length=10, verbose_name='isbn'),
        ),
    ]
