# Generated by Django 5.0 on 2024-08-02 14:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isbn',
            field=models.CharField(default='None', max_length=13, validators=[app.models.validate_isbn_length], verbose_name='isbn'),
        ),
    ]
